-- ATIVIDADE ONLINE03
-- USUARIO1
INSERT INTO USUARIOS VALUES ('ATOS','SENHA123');

-- CLASSE
INSERT INTO CLASSES VALUES ('MONGE','DESCRICAO DO MONGE');

-- HABILIDADES
INSERT INTO HABILIDADES VALUES ('RECUPERAR A VIDA');

-- PERSONAGENS
INSERT INTO PERSONAGENS VALUES ('BITBUG',2,2);
INSERT INTO CLASSEHABILIDADES VALUES (2,2),(2,3)


-- USUARIO2
INSERT INTO USUARIOS VALUES ('ALEX','SENHA543');

-- CLASSE
INSERT INTO CLASSES VALUES ('BARBARO','DESCRICAO DO BARBARO');

-- HABILIDADES
INSERT INTO HABILIDADES VALUES ('LANÇA MORTAL'), ('ESCUDO SUPREMO');

-- PERSONAGENS
INSERT INTO PERSONAGENS VALUES ('DEU BUG',1,1);
INSERT INTO CLASSEHABILIDADES VALUES (1,1),(1,2)